# Fix line endings in Windows. (runs before repo cloning)
#
version: "{build}"

os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

environment:
  qiniu_ACCESS_KEY:
    secure: T10k13x11WzEOXvMqo8pXNK4fMb2+iSqj6ate+fhL7pwWxySeKhsoxjZ2GpAAsBU
  qiniu_SECRET_KEY:
    secure: XRWyQSCo7yWHH7LN5AUlFd3UYl/T6ZAc7WiK4NJJGAKocvmEm7ait8jm+y51CZ6c
  matrix:
    - nodejs_version: 0.10.36
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 0.10.36
      platform: x64
      msvs_toolset: 12

install:
  # use 64 bit python if platform is 64 bit
  - if "%platform%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - if %platform% == x64 CALL "%VS120COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
  - if %platform% == x86 CALL "%VS120COMNTOOLS%..\..\VC\vcvarsall.bat" amd64_x86
  - npm install semver
  - npm install qiniu
  - npm install rc
  - npm install nan
  - npm run publishbinary


build: OFF
test: OFF
deploy: OFF
