# Fix line endings in Windows. (runs before repo cloning)
#
version: "{build}"

os: Visual Studio 2014 CTP4

init:
  - git config --global core.autocrlf input

environment:
  qiniu_ACCESS_KEY:
    secure: T10k13x11WzEOXvMqo8pXNK4fMb2+iSqj6ate+fhL7pwWxySeKhsoxjZ2GpAAsBU
  qiniu_SECRET_KEY:
    secure: XRWyQSCo7yWHH7LN5AUlFd3UYl/T6ZAc7WiK4NJJGAKocvmEm7ait8jm+y51CZ6c
  matrix:
    - nodejs_version: 4.2.0
      platform: x86
      msvs_toolset: 14
    - nodejs_version: 4.2.0
      platform: x64
      msvs_toolset: 14



install:
  # - ps: Install-Product node $env:nodejs_version
  # - node -v
  # - npm install async
  # - npm install decree
  # - npm install nan
  # - npm install qiniu
  # - npm install rc
  # - npm install semver
  #- npm run publishbinary

  # add local node to path (since we install it for msvs_toolset == 14)
  - SET PATH=%CD%;%PATH%;
  # add local node-pre-gyp dir to path
  - SET PATH=node_modules\.bin;%PATH%
  # use 64 bit python if platform is 64 bit
  - if "%platform%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - SET ARCHPATH=
  - if %platform% == x64 (SET ARCHPATH=x64/)
  # install node version per visual studio toolset
  - if "%msvs_toolset%" == "12" powershell Update-NodeJsInstallation $env:nodejs_version $env:platform
  - if "%msvs_toolset%" == "14" powershell Write-Output "fetching https://mapbox.s3.amazonaws.com/node-cpp11/v$env:nodejs_version/${env:ARCHPATH}node.exe"
  - if "%msvs_toolset%" == "14" powershell Start-FileDownload "https://mapbox.s3.amazonaws.com/node-cpp11/v$env:nodejs_version/${env:ARCHPATH}node.exe"
  # only needed if not using 'os: Visual Studio 2014 CTP4'
  #- if "%msvs_toolset%" == "14" powershell Write-Output "https://mapbox.s3.amazonaws.com/node-cpp11/vcredist_$env:platform.exe"
  #- if "%msvs_toolset%" == "14" powershell Start-FileDownload "https://mapbox.s3.amazonaws.com/node-cpp11/vcredist_$env:platform.exe"
  #- if "%msvs_toolset%" == "14" .\vcredist_%platform%.exe /q /norestart
  - ls env:
  - node -v
  - node -e "console.log(process.argv,process.execPath)"
  - npm -v
  # clear out node-gyp header cache
  - if "%msvs_toolset%" == "14" rd /s /q %USERPROFILE%\.node-gyp
  - SET PATH=C:\Program Files (x86)\MSBuild\%msvs_toolset%.0\bin;%PATH%
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\bin;%PATH%
  - if %platform% == x64 CALL "C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\vcvarsall.bat" amd64
  - if %platform% == x86 CALL "C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\vcvarsall.bat" amd64_x86
  - npm install --build-from-source --msvs_version=2013 %BUILD_ARGS% --loglevel=http
  - node_modules\.bin\node-pre-gyp reveal module --silent > module.txt
  - SET /p MODULE=<module.txt
  - del module.txt
  - node -e "console.log(process.execPath)" > node_path.txt
  - SET /p NODE_EXE_PATH=<node_path.txt
  - del node_path.txt
  # should display MSVCP140.dll if built with visual studio 2014 and /MD
  - dumpbin /DEPENDENTS "%NODE_EXE_PATH%" || true
  - dumpbin /DEPENDENTS "%MODULE%" || true
  # make commit message env var shorter
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  # - node publish.js --build



build: OFF
test: OFF
deploy: OFF
