# Fix line endings in Windows. (runs before repo cloning)
#
version: "{build}"

os: Visual Studio 2014 CTP4

init:
  - git config --global core.autocrlf input

environment:
  ACCESS_KEY1: eUnT85Y_aAbKlYuvgBftLO1AvdjzBEf_e2MA3P2I

  ACCESS_KEY:
    secure: eUnT85Y_aAbKlYuvgBftLO1AvdjzBEf_e2MA3P2I
  SECRET_KEY:
    secure: zs7hNvA5LimBYklHP-OAwFdhZg_ik6oOBb52vWaG
  matrix:
    - nodejs_version: 4.2.0
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 4.2.0
      platform: x64
      msvs_toolset: 12



install:
  - ps: Install-Product node $env:nodejs_version
  - node -v
  #- npm install async
  #- npm install decree
  #- npm install nan
  #- npm install qiniu
  #- npm install rc
  #- npm install semver
  #- npm run publishbinary
  - node publish.js --build


build: OFF
test: OFF
deploy: OFF
